#!/bin/bash

# ------- volume --------------
STRVOL="`pactl get-sink-volume @DEFAULT_SINK@ | grep Volume: | cut -f2  -d '/' | xargs`"
if [ "$STRVOL" = "0%"  ]; then
	STRVOL="ﳌ  ${STRVOL}" 
else
	STRVOL="ﱛ ${STRVOL}" # ﳌ    ﱛ  
fi
SPR="      "
STRVOL="${STRVOL}${SPR:${#STRVOL}}"

# --------- brightness -------------
STRBRT="☀ `brightnessctl | egrep "Current brightness" | cut -d '(' -f2 | cut -d ')' -f1 `"
SPR="      "
STRBRT="${STRBRT}${SPR:${#STRBRT}}"

STRDATE=" `date +"%I:%M %p %a %b %_d"` "

STATUS="┊  ${STRVOL} ${STRBRT} ┊ ${STRDATE} ┊ "
xsetroot -name "${STATUS}"
